workflows:
  android-release:
    name: Build Noor+ Android (AAB)
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - flutter pub get
      - flutter build appbundle --release --no-shrink
    artifacts:
      - build/app/outputs/bundle/release/app-release.aab
